#✅✅✅✅ START OF TENSORFLOW BASICS ✅✅✅✅






### ⚫ Tensor with 

```
tf.constant() 
```

In [ ]:
# Importing tensorflow
import tensorflow as tf
print(tf.__version__)


2.7.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Dimensions of tensor
scalar.ndim

0

In [ ]:
# Creating a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Dimension of a vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant ([[10, 7], [69, 420]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,   7],
       [ 69, 420]], dtype=int32)>

In [ ]:
# Dimension of a matrix
matrix.ndim


2

In [ ]:
# Matrix with specified dtype
matrix_2 = tf.constant([[10.,7.], [19., 24.], [69., 420.]] , dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 10.,   7.],
       [ 19.,  24.],
       [ 69., 420.]], dtype=float16)>

In [ ]:
 # Dimension of tensor
 matrix_2.ndim

2

In [ ]:
# Creating a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
# Dimension of tensor
tensor.ndim

3

### ⚫ Tensor with 
```
tf.Variable
```



In [ ]:
# Create the same tensor as above but changeable
tensor_2 = tf.Variable([10,10])
tensor_2[0].assign(7)
print(tensor_2)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>


### ⚫ Creating a random tensor to initialize a neural network

In [ ]:

random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###⚫ Shuffle a random tensor generated
Used to randomize tensors to adapt the NN to the varied coonditions we generate


In [ ]:
unshuffled = tf.constant([[1,2],[3,4]])
tf.random.shuffle(unshuffled, seed= 42)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2]], dtype=int32)>

In [ ]:
# Excersise

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(7,8))
tf.random.shuffle(random_1, seed=12)

random_2 = tf.random.Generator.from_seed(37)
random_2 = random_2.normal(shape=(10, 12))
tf.random.shuffle(random_2, seed=8)



<tf.Tensor: shape=(10, 12), dtype=float32, numpy=
array([[ 0.4604257 ,  0.514933  , -0.06519881, -1.442522  , -0.48492542,
        -1.8364043 ,  0.91463274,  0.5145402 ,  0.5517507 , -0.3741098 ,
        -0.28709963,  1.5089895 ],
       [-1.5780283 , -0.92161775,  0.268676  ,  0.9418312 , -0.9465717 ,
        -0.7108357 ,  1.2995545 , -0.6149066 , -1.4713507 , -0.10086866,
         0.9603877 , -1.6370124 ],
       [ 0.17664973, -0.67038715, -0.503455  , -1.203792  , -2.5255601 ,
         0.05080947,  1.7212061 , -0.6575125 ,  0.7939443 ,  1.3212339 ,
         0.34584793, -0.6699328 ],
       [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ,  0.45331386,
         1.1487608 , -1.2659091 , -0.47450137,  2.006022  ,  0.28288034,
        -0.30288252, -1.443651  ],
       [-0.04082382,  2.6791053 ,  1.0914806 ,  0.33149615, -0.67958915,
         0.44723678, -0.17811584,  0.24882518,  0.49689844,  0.8259971 ,
         1.0340209 , -0.24918637],
       [ 1.6874489 , -0.4462975 , -2.3410842 

### ⚫ Understanding keys
to make tensors reproducibly random keep global and function specifc seed same. 

In [ ]:
tf.ones([10,2])
tf.zeros([10,2])


<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### ⚫ Numpy arrays into tensor & shaping arrays when converting to tensors


In [ ]:
import numpy as np
A = np.arange(1,31, dtype=np.int32)
tf.constant(A, shape=(2,3,5))


<tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]], dtype=int32)>

### ⚫ Tensor Data 

* Shape
* Rank
* Axis/Dimension
* Size




In [ ]:
rank_4_tensor = tf.zeros(shape=[3,2,3,4])
rank_4_tensor

<tf.Tensor: shape=(3, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0] , rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], dtype=float32)>,
 TensorShape([3, 2, 3, 4]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=72>)

In [ ]:
# Various attribute of our tensor
print(f'Datatype of every element: {rank_4_tensor.dtype}')
print(f'Number of dimensions (rank): {rank_4_tensor.ndim}')
print(f'Shape of tensor: {rank_4_tensor.shape}')
print(f'Elements along 0th axis: {rank_4_tensor.shape[0]}')
print(f'Total elements: {tf.size(rank_4_tensor).numpy()}')

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (3, 2, 3, 4)
Elements along 0th axis: 3
Total elements: 72


### ⚫ Indexing tensors
Indexing on tensors is like python list

 

In [ ]:
# First two elements of each dimensions
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get first element from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Adding extra dimensions to a tensor
rank_2_tensor = tf.constant([[1,2,3,4], [1,2,3,4]])
rank_2_tensor , rank_2_tensor.ndim
rank_2_tensor[:, -1]

# Method 1
rank_3_tensor = rank_2_tensor[... , tf.newaxis]

# Method 2
rank_3_tensor_1 = tf.expand_dims(rank_2_tensor, axis=-1) # -1 Expands on the last axis and 0 expands on the first axis


###⚫ Tensor Manipulation

1. Add
2. Mul
3. Sub
4. Divide

In [ ]:
# Scalar ops to tensor

tensor = tf.constant([[10, 15],[12, 43]])
print(tensor + 10)  # tf.math.add
print(tensor * 10)  # tf.math.multiply
print(tensor / 10)  # 
print(tensor - 10)  # tf.math.subtract


tf.Tensor(
[[20 25]
 [22 53]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 150]
 [120 430]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  1.5]
 [1.2 4.3]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[ 0  5]
 [ 2 33]], shape=(2, 2), dtype=int32)


In [ ]:
# Matrix multiplication in tensors
tf.matmul(tensor, tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 280,  795],
       [ 636, 2029]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator "@"
# Note tensor * tensor is element wise multiplication

A = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
B = tf.constant([[3,5],[6,7],[1,8]])

print(A@B)

tf.Tensor(
[[20 59]
 [34 57]
 [30 60]], shape=(3, 2), dtype=int32)


In [ ]:
# Matrix multiplication using tf.tensordot()
tf.tensordot(A, B, axes=1 )

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

###⚫ Changing tensor Datatype

In [ ]:
A.dtype #A is of int.32
C = tf.cast(A, dtype=tf.int16)
C.dtype

tf.int16

### ⚫ Aggregation of tensors

condense a multivalued tensor into a single valued tensor

In [ ]:
# Get absolute value of the tensor
B = tf.constant([[-1+2j, -3+2j],[4-5j, 8-9j]])
tf.abs(B)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 2.23606798,  3.60555128],
       [ 6.40312424, 12.04159458]])>

###⚫ Aggregation operations:

* Minimum of tensor
* Maxium of tensor
* Mean of the tensor
* Sum of the tensor
* Squaring
* Logrithmic
* Square Root

In [ ]:
tensor = tf.constant([[1,2,3,4],[3,8,9,7],[8,4,5,6]])
a=tf.math.reduce_mean(tensor).numpy() # for finding mean
b=tf.math.reduce_max(tensor).numpy() # for finding the max number of the tensor
c=tf.math.reduce_min(tensor).numpy() # for finding the min number of the tensor
d=tf.math.reduce_sum(tensor).numpy() # sum of all elements of a tensor
e=tf.math.reduce_std(tf.cast(tensor, dtype=tf.float32)).numpy() #to find the standard deviation of the tensor
f=tf.math.reduce_variance(tf.cast(tensor, dtype=tf.float32)).numpy() #to find the standard deviation of the tensor
g=tf.math.square(tensor).numpy() # To square a tensor 
h=tf.math.sqrt(tf.cast(tensor, dtype=tf.float32)).numpy() # To root a tensor
i=tf.math.log(tf.cast(tensor, dtype=tf.float32)).numpy() # log of a tensor
print(a,b,c,d, e, f, g, h, i)

5 9 1 60 2.4832773 6.1666665 [[ 1  4  9 16]
 [ 9 64 81 49]
 [64 16 25 36]] [[0.99999994 1.4142134  1.7320508  1.9999999 ]
 [1.7320508  2.8284268  2.9999998  2.6457512 ]
 [2.828427   2.         2.236068   2.4494898 ]] [[0.        0.6931472 1.0986123 1.3862944]
 [1.0986123 2.0794415 2.1972246 1.9459102]
 [2.0794415 1.3862944 1.609438  1.7917595]]


### ⚫ How to find Positional Maximum and Minimum in the tensor

Representation outputs by neural networs are a set of probabilities hence we can use these methods to find positional maximum and minimum. Returns position of max values in tensor.


In [ ]:
test = tf.random.uniform(shape=[1, 1,1,1,1,1,1,1,40])

# Squeezing a matrix, removing all dimensions of value 1
test = tf.squeeze(test)
print(test)

# Finding position of larget number
tf.argmax(test)

# Finding position of smallest number
tf.argmin(test)



tf.Tensor(
[0.09674799 0.38909578 0.75339603 0.67742276 0.8221277  0.2768438
 0.23814607 0.33667147 0.03924799 0.00318229 0.6316972  0.29390514
 0.90486956 0.09387946 0.51780474 0.7727573  0.3184322  0.23611414
 0.37167048 0.9329841  0.30401993 0.6794492  0.2795689  0.6100912
 0.31233037 0.8620124  0.9460925  0.17289138 0.72603285 0.6148132
 0.48730326 0.6032548  0.9755868  0.58193326 0.36142373 0.30157566
 0.5834217  0.42353165 0.27804422 0.19161344], shape=(40,), dtype=float32)


<tf.Tensor: shape=(), dtype=int64, numpy=9>

### 🔴 One Hot Encoding

Form of encoding actual data into numerical data

In [ ]:
random_list = [0,1,2,3]

# One hot encode of the list
tf.one_hot(random_list, depth=len(random_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(random_list, len(random_list), on_value='YES', off_value='NO')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'YES', b'NO', b'NO', b'NO'],
       [b'NO', b'YES', b'NO', b'NO'],
       [b'NO', b'NO', b'YES', b'NO'],
       [b'NO', b'NO', b'NO', b'YES']], dtype=object)>

#❌❌❌❌ END OF TENSORFLOW BASICS ❌❌❌❌